name: climate
channels:
  - conda-forge
dependencies:
  - aiohttp=3.8.3
  - python=3.9.10
  - cartopy=0.20.0
  - cdsapi=0.5.1
  - cftime=1.5.2
  - dask=2022.2.0
  - esgf-pyclient=0.3.1
  - jupyter=1.0.0
  - nb_conda=2.2.1
  - nc-time-axis=1.4.0
  - nco=5.0.7
  - netcdf4=1.5.8
  - numpy=1.22.2
  - matplotlib=3.5.1
  - pandas=1.4.1
  - pynco=1.0.0
  - regionmask=0.8.0
  - scipy=1.8.0
  - seaborn=0.11.2
  - statsmodels=0.13.2
  - urllib3=1.26.8
  - xarray=0.21.1
  - xesmf=0.6.2
